services:
  db:
    image: mariadb:10.11
    mem_limit: ${DB_MEM_LIMIT}
    container_name: ${PROJECT_NAME}_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_INITDB_SKIP_TZINFO: 1
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d:ro
    networks:
      - backend
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    profiles: ["tools"]
    container_name: ${PROJECT_NAME}_pma
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: ${UPLOAD_MAX}
    ports:
      - "127.0.0.1:8080:80"
    networks:
      - backend
    mem_limit: 256m
    depends_on:
      db:
        condition: service_healthy

  nginx:
    mem_limit: ${NGINX_MEM_LIMIT:-256m}
    image: nginx:1.29.6-alpine
    container_name: ${PROJECT_NAME}_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/nginx/certs:ro
      - letsencrypt_www:/var/www/letsencrypt
    networks:
      - backend
      - frontend

  redis:
    image: redis:alpine
    container_name: ${PROJECT_NAME}_redis
    restart: always
    mem_limit: ${REDIS_MEM_LIMIT}
    command: >
      redis-server
      --maxmemory ${REDIS_MAXMEMORY}
      --maxmemory-policy allkeys-lru
      --requirepass ${REDIS_PASSWORD}
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "--no-auth-warning", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  certbot:
    image: certbot/certbot:v4
    profiles: ["ssl"]
    volumes:
      - ./certs:/etc/letsencrypt
      - letsencrypt_www:/var/www/letsencrypt
    networks:
      - frontend

volumes:
  db_data:
  letsencrypt_www:

networks:
  frontend:
  backend:
